# Generated by Django 5.2 on 2025-11-07 10:00

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='код подтверждения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время создания кода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='email подтвержден'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message="Введите номер телефона в формате: '+72345678901' — '+7' и ровно 10 цифр.", regex='^\\+?7?\\d{10}$')], verbose_name='номер телефона'),
        ),
    ]
