# Generated by Django 5.2 on 2025-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_theme',
            field=models.BooleanField(default=False, verbose_name='темная тема'),
        ),
    ]
