# Generated by Django 5.2 on 2025-11-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Координаты определяются автоматически по адресу', null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='studio',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Координаты определяются автоматически по адресу', null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='city',
            field=models.CharField(max_length=50, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='street',
            field=models.CharField(max_length=50, verbose_name='улица'),
        ),
    ]
