# Generated by Django 5.2 on 2025-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_studio_latitude_studio_longitude_alter_studio_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='building',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='street',
        ),
        migrations.AddField(
            model_name='studio',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='полный адрес'),
        ),
    ]
